# Generated by Django 4.2.7 on 2023-11-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='question',
            new_name='busstop',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='busstop',
            name='bus_company',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_text',
            field=models.CharField(default='Undefined', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busstop',
            name='busstop_name',
            field=models.CharField(max_length=64),
        ),
    ]
