# Generated by Django 4.2.7 on 2023-11-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0002_rename_question_destination_busstop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='bus_company',
            field=models.IntegerField(choices=[(1, 'Hanshin'), (2, 'Kyoto City'), (3, 'Hoop')], default=1),
        ),
    ]
