# Generated by Django 4.2.7 on 2023-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0003_alter_busstop_bus_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='approach_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='busstop_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_text',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
