# Generated by Django 4.2.7 on 2023-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0005_alter_destination_approach_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='bus_company',
            field=models.TextField(choices=[('hanshin', 'Hanshin'), ('kyoto_city', 'Kyoto City'), ('hoop', 'Hoop')], default='hanshin'),
        ),
    ]
