# Generated by Django 4.2.7 on 2023-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0006_alter_busstop_bus_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='map_link',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
