# Generated by Django 4.2.7 on 2023-11-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0007_busstop_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destination_text',
            new_name='destination_name',
        ),
    ]
