# Generated by Django 4.2.7 on 2023-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0008_rename_destination_text_destination_destination_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
