# Generated by Django 4.2.7 on 2023-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0009_busstop_order_destination_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
