# Generated by Django 4.2.7 on 2023-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0010_alter_destination_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='bus_company',
            field=models.TextField(choices=[('hanshin', 'Hanshin'), ('kyoto_city', 'Kyoto City'), ('hoop', 'Hoop'), ('kyoto_bus', 'Kyoto Bus')], default='hanshin'),
        ),
    ]
