# Generated by Django 4.2.7 on 2024-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0012_alter_busstop_bus_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='system_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
