# Generated by Django 4.2.7 on 2024-11-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0015_alter_destination_busstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='busstop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approach.busstop'),
        ),
    ]
