# Generated by Django 5.1.3 on 2025-02-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approach', '0018_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
